/**
 * M-5: Fallback when Playwright is unavailable — minimal PDF via pdf-lib.
 */

import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

// Fallback implementation may ignore HTML; signature kept for interface compatibility.
export async function createPdfFromHtml(_html: string): Promise<Buffer> {
  void _html;
  const doc = await PDFDocument.create();
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const page = doc.addPage([595, 842]); // A4
  page.drawText("Mentorship Engagement Contract", {
    x: 50,
    y: 800,
    size: 16,
    font,
    color: rgb(0.06, 0.1, 0.06),
  });
  page.drawText("This document was generated by Ascend. Full contract terms are available on the platform.", {
    x: 50,
    y: 760,
    size: 10,
    font,
    color: rgb(0.2, 0.2, 0.2),
  });
  const pdfBytes = await doc.save();
  return Buffer.from(pdfBytes);
}
