/**
 * Phase 17: Audit action constants — single source of truth for audit action strings.
 */

export const AUDIT_ACTIONS = {
  // AUTH
  AUTH_LOGIN_SUCCESS: "AUTH_LOGIN_SUCCESS",
  AUTH_LOGIN_FAILED: "AUTH_LOGIN_FAILED",
  AUTH_LOGOUT: "AUTH_LOGOUT",
  AUTH_OAUTH_SUCCESS: "AUTH_OAUTH_SUCCESS",
  AUTH_PASSWORD_RESET_REQUESTED: "AUTH_PASSWORD_RESET_REQUESTED",
  AUTH_PASSWORD_RESET_COMPLETED: "AUTH_PASSWORD_RESET_COMPLETED",
  AUTH_EMAIL_VERIFIED: "AUTH_EMAIL_VERIFIED",
  AUTH_2FA_ENABLED: "AUTH_2FA_ENABLED",
  AUTH_2FA_DISABLED: "AUTH_2FA_DISABLED",
  AUTH_SESSION_INVALIDATED: "AUTH_SESSION_INVALIDATED",

  // DATA ACCESS
  RESUME_DOWNLOADED: "RESUME_DOWNLOADED",
  PROFILE_VIEWED_BY_RECRUITER: "PROFILE_VIEWED_BY_RECRUITER",
  SALARY_DATA_ACCESSED: "SALARY_DATA_ACCESSED",
  CONTRACT_PDF_DOWNLOADED: "CONTRACT_PDF_DOWNLOADED",
  CANDIDATE_CONTACT_VIEWED: "CANDIDATE_CONTACT_VIEWED",

  // DATA MUTATION
  PROFILE_UPDATED: "PROFILE_UPDATED",
  JOB_POST_CREATED: "JOB_POST_CREATED",
  JOB_POST_UPDATED: "JOB_POST_UPDATED",
  JOB_POST_CLOSED: "JOB_POST_CLOSED",
  APPLICATION_SUBMITTED: "APPLICATION_SUBMITTED",
  APPLICATION_WITHDRAWN: "APPLICATION_WITHDRAWN",
  REVIEW_SUBMITTED: "REVIEW_SUBMITTED",
  ACCOUNT_SETTINGS_CHANGED: "ACCOUNT_SETTINGS_CHANGED",

  // MENTORSHIP
  CONTRACT_GENERATED: "CONTRACT_GENERATED",
  CONTRACT_SIGNED: "CONTRACT_SIGNED",
  CONTRACT_VOIDED: "CONTRACT_VOIDED",
  ESCROW_FUNDED: "ESCROW_FUNDED",
  ESCROW_RELEASED: "ESCROW_RELEASED",
  ESCROW_FROZEN: "ESCROW_FROZEN",
  SESSION_STARTED: "SESSION_STARTED",
  SESSION_COMPLETED: "SESSION_COMPLETED",
  STENO_RECORD_GENERATED: "STENO_RECORD_GENERATED",
  DISPUTE_FILED: "DISPUTE_FILED",
  DISPUTE_RESOLVED: "DISPUTE_RESOLVED",

  // PAYMENT
  PAYMENT_INITIATED: "PAYMENT_INITIATED",
  PAYMENT_COMPLETED: "PAYMENT_COMPLETED",
  PAYMENT_FAILED: "PAYMENT_FAILED",
  REFUND_INITIATED: "REFUND_INITIATED",
  SUBSCRIPTION_CREATED: "SUBSCRIPTION_CREATED",
  SUBSCRIPTION_CANCELLED: "SUBSCRIPTION_CANCELLED",

  // ADMIN
  USER_BANNED: "USER_BANNED",
  USER_UNBANNED: "USER_UNBANNED",
  COMPANY_VERIFIED: "COMPANY_VERIFIED",
  COMPANY_SUSPENDED: "COMPANY_SUSPENDED",
  REVIEW_APPROVED: "REVIEW_APPROVED",
  REVIEW_REJECTED: "REVIEW_REJECTED",
  FEATURE_FLAG_CHANGED: "FEATURE_FLAG_CHANGED",
  MENTOR_VERIFICATION_APPROVED: "MENTOR_VERIFICATION_APPROVED",
  MENTOR_VERIFICATION_REJECTED: "MENTOR_VERIFICATION_REJECTED",
  DISPUTE_MANUALLY_REVIEWED: "DISPUTE_MANUALLY_REVIEWED",
  DATA_REQUEST_PROCESSED: "DATA_REQUEST_PROCESSED",

  // COMPLIANCE
  DATA_EXPORT_REQUESTED: "DATA_EXPORT_REQUESTED",
  DATA_EXPORT_COMPLETED: "DATA_EXPORT_COMPLETED",
  ACCOUNT_DELETION_REQUESTED: "ACCOUNT_DELETION_REQUESTED",
  ACCOUNT_DELETION_COMPLETED: "ACCOUNT_DELETION_COMPLETED",

  // SECURITY
  RATE_LIMIT_HIT: "RATE_LIMIT_HIT",
  INVALID_TOKEN_USED: "INVALID_TOKEN_USED",
  SUSPICIOUS_ACTIVITY_DETECTED: "SUSPICIOUS_ACTIVITY_DETECTED",
} as const;
