import { PrismaClient } from "@prisma/client";
import * as fs from "fs";
import * as path from "path";

const prisma = new PrismaClient();

// Normalise role titles to canonical groups
const ROLE_GROUPS: Record<string, string> = {
  "product manager": "Product Manager",
  "senior product manager": "Product Manager",
  "product owner": "Product Manager",
  "associate product manager": "Product Manager",
  "software engineer": "Software Engineer",
  "software developer": "Software Engineer",
  "backend developer": "Software Engineer",
  "frontend developer": "Frontend Engineer",
  "full stack developer": "Full Stack Engineer",
  "data scientist": "Data Scientist",
  "data analyst": "Data Analyst",
  "business analyst": "Business Analyst",
  "marketing manager": "Marketing Manager",
  "devops engineer": "DevOps Engineer",
  "ux designer": "UX Designer",
  "ui designer": "UX Designer",
  "product designer": "UX Designer",
  "hr manager": "HR Manager",
  "human resources": "HR Manager",
  "finance analyst": "Finance Analyst",
  "financial analyst": "Finance Analyst",
  "sales manager": "Sales Manager",
  "account manager": "Sales Manager",
};

function normaliseRole(title: string): string {
  const lower = title.toLowerCase().trim();
  for (const [pattern, canonical] of Object.entries(ROLE_GROUPS)) {
    if (lower.includes(pattern)) return canonical;
  }
  // Fallback: title-case the original
  return title
    .split(" ")
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
    .join(" ");
}

async function generateTaxonomy() {
  console.log("Loading ParsedJDs...");
  const parsedJDs = await prisma.parsedJD.findMany({
    select: {
      title: true,
      seniority: true,
      skills: true,
      keywords: true,
    },
  });

  console.log(`Processing ${parsedJDs.length} parsed JDs...`);

  // keyword frequency: role → keyword → count
  const keywordsByRole: Record<string, Record<string, number>> = {};
  // skills frequency: role → skill → count
  const skillsByRole: Record<string, Record<string, number>> = {};
  // role counts for minimum threshold
  const roleCounts: Record<string, number> = {};

  for (const jd of parsedJDs) {
    const role = normaliseRole(jd.title);
    if (!keywordsByRole[role]) keywordsByRole[role] = {};
    if (!skillsByRole[role]) skillsByRole[role] = {};
    roleCounts[role] = (roleCounts[role] || 0) + 1;

    // Keywords
    for (const kw of (jd.keywords as string[])) {
      const k = kw.toLowerCase().trim();
      if (k.length > 2) {
        keywordsByRole[role][k] = (keywordsByRole[role][k] || 0) + 1;
      }
    }

    // Skills
    const skills = jd.skills as { mustHave: string[]; niceToHave: string[] };
    for (const skill of [...(skills.mustHave || []), ...(skills.niceToHave || [])]) {
      const s = skill.trim();
      if (s.length > 1) {
        skillsByRole[role][s] = (skillsByRole[role][s] || 0) + 1;
      }
    }
  }

  // Filter to roles with at least 10 JDs
  const qualifiedRoles = Object.keys(roleCounts).filter((r) => roleCounts[r] >= 10);
  console.log(`Roles with 10+ JDs: ${qualifiedRoles.length}`);

  // Build keywords output: top 30 per role, sorted by frequency
  const keywordsOutput: Record<string, Array<{ keyword: string; count: number }>> = {};
  for (const role of qualifiedRoles) {
    keywordsOutput[role] = Object.entries(keywordsByRole[role])
      .sort(([, a], [, b]) => b - a)
      .slice(0, 30)
      .map(([keyword, count]) => ({ keyword, count }));
  }

  // Build skills output: top 25 per role
  const skillsOutput: Record<
    string,
    Array<{ skill: string; count: number; frequency: number }>
  > = {};
  for (const role of qualifiedRoles) {
    const total = roleCounts[role];
    skillsOutput[role] = Object.entries(skillsByRole[role])
      .sort(([, a], [, b]) => b - a)
      .slice(0, 25)
      .map(([skill, count]) => ({
        skill,
        count,
        frequency: Math.round((count / total) * 100), // % of JDs mentioning this skill
      }));
  }

  // Write keywords-by-role.ts
  const keywordsFile = `// AUTO-GENERATED by scripts/ingestion/generate-taxonomy.ts
// Do not edit manually. Re-run the script to update.
// Generated: ${new Date().toISOString()}
// Source: ${parsedJDs.length} parsed JDs across ${qualifiedRoles.length} roles

export const KEYWORDS_BY_ROLE: Record<string, Array<{ keyword: string; count: number }>> = ${JSON.stringify(keywordsOutput, null, 2)}
`;

  // Write skills-taxonomy.ts
  const skillsFile = `// AUTO-GENERATED by scripts/ingestion/generate-taxonomy.ts
// Do not edit manually. Re-run the script to update.
// Generated: ${new Date().toISOString()}
// Source: ${parsedJDs.length} parsed JDs across ${qualifiedRoles.length} roles

export const SKILLS_BY_ROLE: Record<string, Array<{ skill: string; count: number; frequency: number }>> = ${JSON.stringify(skillsOutput, null, 2)}

// Helper: get top N skills for a role (frequency >= minFrequency%)
export function getTopSkillsForRole(role: string, n = 15, minFrequency = 10): string[] {
  const skills = SKILLS_BY_ROLE[role] || []
  return skills
    .filter(s => s.frequency >= minFrequency)
    .slice(0, n)
    .map(s => s.skill)
}

// Helper: check if a skill is common for a role
export function isSkillCommonForRole(role: string, skill: string, minFrequency = 20): boolean {
  const skills = SKILLS_BY_ROLE[role] || []
  const match = skills.find(s => s.skill.toLowerCase() === skill.toLowerCase())
  return match ? match.frequency >= minFrequency : false
}
`;

  fs.mkdirSync(path.join(process.cwd(), "lib/data"), { recursive: true });
  fs.writeFileSync(path.join(process.cwd(), "lib/data/keywords-by-role.ts"), keywordsFile);
  fs.writeFileSync(path.join(process.cwd(), "lib/data/skills-taxonomy.ts"), skillsFile);

  console.log("\n═══ Taxonomy generation complete ═══");
  console.log(`✓ lib/data/keywords-by-role.ts — ${qualifiedRoles.length} roles`);
  console.log(`✓ lib/data/skills-taxonomy.ts — ${qualifiedRoles.length} roles`);
  console.log("\nTop roles by JD count:");
  Object.entries(roleCounts)
    .sort(([, a], [, b]) => b - a)
    .slice(0, 10)
    .forEach(([role, count]) => console.log(`  ${role}: ${count} JDs`));

  await prisma.$disconnect();
}

generateTaxonomy().catch((err) => {
  console.error(err);
  process.exit(1);
});
